/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EquipmentAssignation;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Karen
 */
public class UserInterface extends javax.swing.JFrame {
Random r = new Random();
    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbx_localidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbt_f = new javax.swing.JRadioButton();
        rbt_m = new javax.swing.JRadioButton();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_id = new javax.swing.JTextPane();
        cbx_1 = new javax.swing.JCheckBox();
        cbx_3 = new javax.swing.JCheckBox();
        cbx_2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(21474, 21474));
        setSize(new java.awt.Dimension(200, 200));
        setState(1);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciente ", "Lugar solicitud", "Fecha solicitud", "Urgencia (ESI)", "Fecha asignada", "Equipo asignado", "Lugar asignado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("jtpPacientes");

        for(int x=0;x<Variables.npatients;x++)
        {   Patient p=new Patient();
            waitinglist.add(p);

            String id = p.id;
            String lugar;
            lugar= "Localidad "+ p.location;

            int urgencia= p.urgency;

            String equipoAsignado="Pendiente";
            String lugarAsignado="Pendiente";

            String date = p.da;

            Object[] row={id, lugar, date, urgencia, "pendiente", equipoAsignado, lugarAsignado};
            DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
            modelo.addRow(row);

        }

        jLabel1.setText("Pacientes");
        jLabel1.setName("lbl_patients"); // NOI18N

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Equipo", "Tipo", "Ubicación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        for (int x=0; x<Variables.nequipments; x++)
        {
            Equipement e= new Equipement();
            equips[x]= new Equipement();

            String id= Integer.toString(x);
            String tipo = "Electrocardiograma";
            String ubicacion = "Localidad" + Integer.toString(e.localization);

            Object[] row={id, tipo, ubicacion};
            DefaultTableModel modelo= (DefaultTableModel) jTable2.getModel();
            modelo.addRow(row);
        }

        jButton1.setText("Simular asignación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Equipos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("Ingreso paciente");

        cbx_localidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LocalidadA", "LocalidadB" }));
        cbx_localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_localidadActionPerformed(evt);
            }
        });

        jLabel3.setText("Lugar origen");

        jLabel4.setText("Sexo");

        jLabel5.setText("Id paciente");

        jLabel6.setText("Seleccione las opciones que correspondan.");

        jLabel7.setText("Edad");

        rbt_f.setText("Femenino");
        rbt_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_fActionPerformed(evt);
            }
        });

        rbt_m.setText("Masculino");

        jScrollPane4.setViewportView(txt_id);

        cbx_1.setText("Necesita atención inmediata para salvar su vida");
        cbx_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_1ActionPerformed(evt);
            }
        });

        cbx_3.setText("Requiere acceso a equipo o medicamento especializado");

        cbx_2.setText("Se encuentra en una situación de alto riesgo");
        cbx_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Su médico validará la urgencia sugerida en este ticket.");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbt_f)
                                .addGap(44, 44, 44)
                                .addComponent(rbt_m))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_3)
                            .addComponent(cbx_2)
                            .addComponent(cbx_1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(65, 65, 65)
                            .addComponent(cbx_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbt_f)
                            .addComponent(rbt_m))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(cbx_1)
                .addGap(18, 18, 18)
                .addComponent(cbx_2)
                .addGap(17, 17, 17)
                .addComponent(cbx_3)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Problem AssigmentP = new Problem(Variables.variables, Variables.objetives);
        Run run = new Run();
        int[] permutation= new int[Variables.npatients];
        
        try {
            permutation = run.Start(AssigmentP);
        } catch (Exception ex) {
            Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i=0; i<permutation.length; i++)
        {
            int idPatient=permutation[i+Variables.fixedPatients];
            int waiting= i%Variables.maxTime;
            Patient patient= waitinglist.get(idPatient);
            int equip=(int) Math.floor(i/Variables.maxTime);
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dt= patient.da;
                      
            Calendar c = Calendar.getInstance();
             try {
                 c.setTime(dFormat.parse(dt));
             } catch (ParseException ex) {
                 Logger.getLogger(UserInterface.class.getName()).log(Level.SEVERE, null, ex);
             }
            c.add(Calendar.DATE, waiting);  // number of days to add
            dt = dFormat.format(c.getTime());  // dt is now the new date
            //4 - fecha
            jTable1.setValueAt(dt, idPatient, 4);
            //5 eqipo
            jTable1.setValueAt(equip, idPatient, 5);
            //6 Lugar
            jTable1.setValueAt("Localidad "+equips[equip].localization, idPatient, 6);
        }
        
        Variables.fixedPatients+=Variables.unmoviledate;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbx_localidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_localidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_localidadActionPerformed

    private void rbt_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_fActionPerformed

    private void cbx_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_1ActionPerformed

    private void cbx_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_2ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       Patient p;
       String id= txt_id.getText();
       int ta=0;
       int urg;
       int loca=cbx_localidad.getSelectedIndex();
        if (cbx_1.isSelected())
            urg=5;
        else
        {
            if(cbx_2.isSelected())
                urg=5;
            else
                if (cbx_3.isSelected())
                    urg=4;
                else
                    urg= r.nextInt(3);
        }
        
        p =new Patient( id, ta, urg, loca);
        
        int new_id= getSimilarPatient(p);
        if (new_id>=0)
        {
        waitinglist.set(new_id, p);
            //id
            jTable1.setValueAt(p.id, new_id, 0);
            //1 logar origen
            jTable1.setValueAt(cbx_localidad.getItemAt(p.location), new_id, 1);
            //2 fecha solicitud
            jTable1.setValueAt(p.da, new_id, 2);
            //3 urgencia
            jTable1.setValueAt(p.urgency, new_id, 3);
        int equipo=  Integer.parseInt( jTable1.getValueAt(new_id, 5).toString() );
        String equipoL=   jTable1.getValueAt(new_id, 6).toString() ;
            String mensaje="Se ha asignado al paciente con el id " +id + " al día " + p.da + " en el equipo con id " + equipo + " en el centro " + equipoL;
        JOptionPane.showMessageDialog(null, mensaje, "Fecha registrada ", JOptionPane.INFORMATION_MESSAGE);

        }
        else
        {
            waitinglist.add(p);
            String mensaje="Por el momento no hay lugares por asignar, se agregará el paciente a la lista del siguiente periodo.";
            JOptionPane.showMessageDialog(null, mensaje, "Fecha registrada ", JOptionPane.INFORMATION_MESSAGE);

        }
            
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    
     List<Patient> waitinglist= new ArrayList<Patient>();
     Equipement[] equips= new Equipement[Variables.nequipments];
        
        
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
        
       
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }
    public   void Start() throws Exception
    {
        for (int x=0; x<100; x++)
        {   Patient p=new Patient(); 
            waitinglist.add(p);
        
            String id = p.id;
            String lugar;
            if (p.location==1)
                lugar="Zona A";
            else
                lugar="Zona B";
            int urgencia= p.urgency;
            
            String equipoAsignado="Pendiente";
            String lugarAsignado="Pendiente";
            SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date d = new Date();
            String date = dFormat.format(d);    

            
            Object[] row={id, lugar, date, urgencia, "pendiente", equipoAsignado, lugarAsignado};
            DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
           modelo.addRow(row);
                   
       
        }
        for (int x=0; x<Variables.nequipments; x++)
        {
            Equipement e= new Equipement();
            equips[x]= new Equipement();
            
            String id= Integer.toString(x);
            String tipo = "Electrocardiograma";
            String ubicacion = "Localidad" + Integer.toString(e.localization);
            
            Object[] row={id, tipo, ubicacion};
            DefaultTableModel modelo= (DefaultTableModel) jTable2.getModel();
           modelo.addRow(row);
        }   
        Problem AssigmentP = new Problem(Variables.variables, Variables.objetives);
        Run run = new Run();
        int[] permutation= run.Start(AssigmentP);
        for (int i=0; i<permutation.length; i++)
        {
            
        }
    }
    
    int getSimilarPatient(Patient p)
    {
        List<Patient> candidatos= new ArrayList<Patient>();
         List<Patient> localidad= new ArrayList<Patient>();
        for (Patient ran: waitinglist)
        {
            if (ran.urgency==p.urgency && ran.id==Variables.Fantasma )
                candidatos.add(ran);
        }
        if (candidatos.isEmpty())
        {
           for (Patient ran: waitinglist)
            {
                if (ran.urgency>=p.urgency && ran.id==Variables.Fantasma )
                    candidatos.add(ran);
            } 
           if (candidatos.size()>1)
           {
               Collections.sort(candidatos, (Patient a1, Patient a2) -> a1.urgency-a2.urgency);
               
           }
           return waitinglist.indexOf(candidatos.get(0));
        }
        
         if(candidatos.size()>1)
            {    for (Patient ran : candidatos)
                {
                    if(ran.location== p.location && ran.ta>= p.ta)
                    {
                        localidad.add(ran);

                    }
                }
                if(localidad.size()>0)
                    candidatos=localidad;
            }
            if (candidatos.size()>1)
                Collections.sort(candidatos, (Patient a1, Patient a2) -> a1.ta-a2.ta);
            if (candidatos.isEmpty())
                return -1;
           
        
         return waitinglist.indexOf(candidatos.get(0));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbx_1;
    private javax.swing.JCheckBox cbx_2;
    private javax.swing.JCheckBox cbx_3;
    private javax.swing.JComboBox<String> cbx_localidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rbt_f;
    private javax.swing.JRadioButton rbt_m;
    private javax.swing.JTextPane txt_id;
    // End of variables declaration//GEN-END:variables
}
